#984: Update form error messages on domain management contacts
cisagov/manage.get.gov pull request #1375
Opened 2023-11-20 23:03 UTC by erinysong

## Ticket

Resolves #984 

## Changes

- Overrides error messages for Contact Form on domain management page. Error messages updated to reflect the [content doc](https://docs.google.com/document/d/1EHMzgmig6vaSFRvCiih87Cx38lD2rWrkEE4BzDzev9Q/edit) (also linked in the issue).
- Creates a child class of ContactForm called AuthorizingOfficialContactForm which specifies custom error messages for Authorizing Official page of domain management page. 

<img width="688" alt="image" src="https://github.com/cisagov/manage.get.gov/assets/121973038/0e427335-9c86-4511-b97a-ce0abc4f76fb">

<img width="710" alt="image" src="https://github.com/cisagov/manage.get.gov/assets/121973038/eb816326-fa32-4491-9c94-f7b745f0e2fd">

## Context for reviewers

## Setup

Go to [staging link](https://getgov-es.app.cloud.gov) and go to manage domain.

- Navigate to Your contact information page and enter empty inputs for required fields. The form should output error messages for the specific fields that were not entered.
- Navigate to Authorizing official page and repeat the same steps as above.

## Code Review Verification Steps

### As the original developer, I have

#### Satisfied acceptance criteria and met development standards

- [ ] Met the acceptance criteria, or will meet them in a subsequent PR
- [ ] Created/modified automated tests
- [ ] Added at least 2 developers as PR reviewers (only 1 will need to approve)
- [ ] Messaged on Slack or in standup to notify the team that a PR is ready for review
- [ ] Changes to “how we do things” are documented in READMEs and or onboarding guide
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the assoicated migrations file has been commited.

#### Ensured code standards are met (Original Developer)

- [ ] All new functions and methods are commented using plain language
- [ ] Did dependency updates in Pipfile also get changed in requirements.txt?
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values

#### Validated user-facing changes (if applicable)

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)
- [ ] Add at least 1 designer as PR reviewer

### As a code reviewer, I have

#### Reviewed, tested, and left feedback about the changes

- [ ] Pulled this branch locally and tested it
- [ ] Reviewed this code and left comments
- [ ] Checked that all code is adequately covered by tests
- [ ] Made it clear which comments need to be addressed before this work is merged
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the assoicated migrations file has been commited.

#### Ensured code standards are met (Code reviewer)

- [ ] All new functions and methods are commented using plain language
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values
- [ ] (Rarely needed) Did dependency updates in Pipfile also get changed in requirements.txt?

#### Validated user-facing changes as a developer

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Meets all designs and user flows provided by design/product
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers, the suggestion is to use ones that the developer didn't (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

**Note:** Multiple code reviewers can share the checklists above, a second reviewers should not make a duplicate checklist

### As a designer reviewer, I have

#### Verified that the changes match the design intention

- [ ] Checked that the design translated visually
- [ ] Checked behavior
- [ ] Checked different states (empty, one, some, error)
- [ ] Checked for landmarks, page heading structure, and links
- [ ] Tried to break the intended flow

#### Validated user-facing changes as a designer

- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

## Screenshots

2023-11-21 00:02 UTC, therealslimhsiehdy requested changes
Maybe I am confused, but I think for Authorizing Official there maybe different errors? This seems like the correct errors for "Your contact information" 😅 

If I'm incorrect, feel free to dismiss the request changes!

2023-11-21 00:15 UTC, erinysong commented on src/registrar/forms/domain.py
> +        self.fields["first_name"].error_messages = {"required": "Enter the first name / given name of this contact."}
hm interesting, you're right that the domain management form for authorizing official has different error messages than the application form. we should make sure that they're consistent and we can ask content which one is preferred. @michelle-rago do you have a preference between which of the 2 error message formats we use for authorizing officials?:

1. Enter the first name / given name of this contact. (what was requested on this [content doc](https://docs.google.com/document/d/1EHMzgmig6vaSFRvCiih87Cx38lD2rWrkEE4BzDzev9Q/edit#heading=h.gjdgxs) and issue)
2. Enter the first name / given name of your authorizing official. (what is currently used on the domain application)

2023-11-21 17:41 UTC, erinysong commented on src/registrar/forms/domain.py
> +    security_email = forms.EmailField(label="Security email (optional)", required=False)
Leftover code from testing something else - thank you for catching that! just removed it

2023-11-21 17:43 UTC, erinysong commented on src/registrar/forms/domain.py
> +        self.fields["first_name"].error_messages = {"required": "Enter the first name / given name of this contact."}
Resolved - everything should be updated to authorizing official text (option 2)

2023-11-21 18:01 UTC, therealslimhsiehdy approved these changes
Looks great for contact + authorizing official! 

<img width="993" alt="Screenshot 2023-11-21 at 9 59 57 AM" src="https://github.com/cisagov/manage.get.gov/assets/13954664/bb8fb2d7-c6e2-4f42-a776-f3c076a0333a">

<img width="996" alt="Screenshot 2023-11-21 at 9 59 44 AM" src="https://github.com/cisagov/manage.get.gov/assets/13954664/5fc21de5-5861-45d4-9937-5d4bec8045fa">

2023-11-21 20:51 UTC, merged

2023-11-22 17:05 UTC, michelle-rago commented on src/registrar/forms/domain.py
> +        self.fields["first_name"].error_messages = {"required": "Enter the first name / given name of this contact."}
I know I'm late on this...just wanted to say "thanks" for picking the more specific set of error messages!