Issue #2271: Start domain request bug (multiple can get created) - [HOTGOV]
cisagov/manage.get.gov pull request #2290
Opened 2024-06-11 02:44 UTC by rachidatecs

## Ticket

Resolves #2271 

## Changes

- Change 1
- Change 2

## Context for reviewers

## Setup

## Code Review Verification Steps

### As the original developer, I have

#### Satisfied acceptance criteria and met development standards

- [ ] Met the acceptance criteria, or will meet them in a subsequent PR
- [ ] Created/modified automated tests
- [ ] Added at least 2 developers as PR reviewers (only 1 will need to approve)
- [ ] Messaged on Slack or in standup to notify the team that a PR is ready for review
- [ ] Changes to “how we do things” are documented in READMEs and or onboarding guide
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the associated migrations file has been commited.

#### Ensured code standards are met (Original Developer)

- [ ] All new functions and methods are commented using plain language
- [ ] Did dependency updates in Pipfile also get changed in requirements.txt?
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values

#### Validated user-facing changes (if applicable)

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)
- [ ] Add at least 1 designer as PR reviewer

### As a code reviewer, I have

#### Reviewed, tested, and left feedback about the changes

- [ ] Pulled this branch locally and tested it
- [ ] Reviewed this code and left comments
- [ ] Checked that all code is adequately covered by tests
- [ ] Made it clear which comments need to be addressed before this work is merged
- [ ] If any model was updated to modify/add/delete columns, makemigrations was ran and the associated migrations file has been commited.

#### Ensured code standards are met (Code reviewer)

- [ ] All new functions and methods are commented using plain language
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values
- [ ] (Rarely needed) Did dependency updates in Pipfile also get changed in requirements.txt?

#### Validated user-facing changes as a developer

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Meets all designs and user flows provided by design/product
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers, the suggestion is to use ones that the developer didn't (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

**Note:** Multiple code reviewers can share the checklists above, a second reviewers should not make a duplicate checklist

### As a designer reviewer, I have

#### Verified that the changes match the design intention

- [ ] Checked that the design translated visually
- [ ] Checked behavior
- [ ] Checked different states (empty, one, some, error)
- [ ] Checked for landmarks, page heading structure, and links
- [ ] Tried to break the intended flow

#### Validated user-facing changes as a designer

- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

- [ ] Tested with multiple browsers (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari

- [ ] (Rarely needed) Tested as both an analyst and applicant user

## Screenshots

2024-06-11 05:22 UTC, abroddrick requested changes
Sorry, but I think this will just result in future tech debt and other issues. We should not use time to determine if we make a new request in our session.

2024-06-12 03:32 UTC, rachidatecs commented
> Sorry, but I think this will just result in future tech debt and other issues. We should not use time to determine if we make a new request in our session.

Revised

2024-06-12 23:46 UTC, abroddrick approved these changes
This solution does feel a bit hacky, but I think it does solve the initial bug that this ticket was made for. It definitely isn't perfect given there are still ways (as noted in the context for reviewers) to still get multiple applications started when the user is only intending to make one. 

I am fine with approving for now, but recommend leaving this PR open for another day or so in case someone else has an idea of a better solution. @dave-kennedy-ecs was thinking of looking at this one so if there is a better way found please feel free to ignore this approval.

2024-06-12 23:46 UTC, abroddrick commented on src/registrar/views/domain_request.py
> +            # unkowingly overrites when she thinks she's working on a
```suggestion
            # unknowingly overwrites when she thinks she's working on a
```

2024-06-13 00:59 UTC, rachidatecs commented
> This solution does feel a bit hacky, but I think it does solve the initial bug that this ticket was made for. It definitely isn't perfect given there are still ways (as noted in the context for reviewers) to still get multiple applications started when the user is only intending to make one.
> 
> I am fine with approving for now, but recommend leaving this PR open for another day or so in case someone else has an idea of a better solution. @dave-kennedy-ecs was thinking of looking at this one so if there is a better way found please feel free to ignore this approval.

ICYMI: else:  Removing self.request.session["new_request"] = True in goto in the wizard might cover the last scenario, but am not sure it's worth dumping that safety net to cover a far-fetched edge case

2024-06-17 19:42 UTC, dave-kennedy-ecs approved these changes
Reviewed code with Rachid and independently.  Tested locally.  Nice work!

2024-06-17 21:34 UTC, merged