[DRAFT] Issue #2975 - domain and domain info portfolio fields
cisagov/manage.get.gov pull request #3044
Opened 2024-11-07 16:50 UTC by CocoByte

## Ticket

Resolves #00

## Changes

- Change 1
- Change 2

## Context for reviewers

## Setup

## Code Review Verification Steps

### As the original developer, I have

#### Satisfied acceptance criteria and met development standards

- [ ] Met the acceptance criteria, or will meet them in a subsequent PR
- [ ] Created/modified automated tests
- [ ] Update documentation in READMEs and/or onboarding guide

#### Ensured code standards are met (Original Developer)

- [ ] If any updated dependencies on Pipfile, also update dependencies in requirements.txt.
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values

#### Validated user-facing changes (if applicable)

- [ ] Tag @dotgov-designers in this PR's Reviewers for design review. If code is not user-facing, delete design reviewer checklist
- [ ] Verify new pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

### As a code reviewer, I have

#### Reviewed, tested, and left feedback about the changes

- [ ] Pulled this branch locally and tested it
- [ ] Verified code meets all checks above. Address any checks that are not satisfied
- [ ] Reviewed this code and left comments. Indicate if comments must be addressed before code is merged
- [ ] Checked that all code is adequately covered by tests
- [ ] Verify migrations are valid and do not conflict with existing migrations

#### Validated user-facing changes as a developer
**Note:** Multiple code reviewers can share the checklists above, a second reviewer should not make a duplicate checklist. All checks should be checked before approving, even those labeled N/A. 

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Meets all designs and user flows provided by design/product
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)
- [ ] (Rarely needed) Tested as both an analyst and applicant user

### As a designer reviewer, I have

#### Verified that the changes match the design intention

- [ ] Checked that the design translated visually
- [ ] Checked behavior. Comment any found issues or broken flows.
- [ ] Checked different states (empty, one, some, error)
- [ ] Checked for landmarks, page heading structure, and links

#### Validated user-facing changes as a designer

- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)
- [ ] Tested with multiple browsers (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari
- [ ] (Rarely needed) Tested as both an analyst and applicant user

### References
- [Code review best practices](../docs/dev-practices/code_review.md)

## Screenshots

2024-11-20 17:42 UTC, abroddrick requested changes
See comments for changes requested and comments. Also I was only running this locally and already noticing a significant slowdown in performance. Can you please put this on a sandbox so we can see if the slow down is just a local oriented thing? If you want to use mine you can.

2024-11-20 17:42 UTC, abroddrick commented on src/registrar/admin.py
> +    # generic_org_type.admin_order_field = "domain_info__generic_org_type"  # type: ignore
remove commented out code

2024-11-20 17:42 UTC, abroddrick commented on src/registrar/admin.py
> +    # federal_agency.admin_order_field = "domain_info__federal_agency"  # type: ignore
remove commented out code

2024-11-20 17:42 UTC, abroddrick commented on src/registrar/models/domain_request.py
> +            return "portfolio name" #self.portfolio.organization_name
**blocking**: looks like the values here should be the comment values

2024-11-20 17:42 UTC, abroddrick commented on src/registrar/models/domain_information.py
> +            return "portoflio name" #self.portfolio.organization_name
Looks like the value here should be the comments

2024-11-20 17:42 UTC, abroddrick commented on src/registrar/admin.py
> +    def get_queryset(self, request):
Why was this moved up? The typical convention I have seen is Class definition, followed by all class variables, then sub classes followed by class functions. We already have this format being broken by defining some variables above sub classes but I would prefer we not make the format even more outside of convention by moving functions up

2024-11-20 17:42 UTC, abroddrick commented on src/registrar/admin.py
> +    @admin.display(description=_("Converted Generic Org Type"))
**changes requested** @CocoByte we don't want this to show as "converted" anywhere for the users. This is not meant to be a user facing change and is meant to make sure users see the correct data and don't need to know how the sauce is made. Please change all the ones like this.

2024-11-20 21:44 UTC, CocoByte commented on src/registrar/admin.py
> +    def dehydrate_organization_name(self, obj):
This is a convention used by django-import-export to override or customize the export behavior for specific fields.  Removing the "dehydrate_" keyword would require us to override the export_resource() method.

2024-11-20 21:44 UTC, CocoByte commented on src/registrar/admin.py
> +    def dehydrate_organization_name(self, obj):
Without these methods, the converted fields will just get ignored.

2024-12-02 19:27 UTC, abroddrick commented on src/registrar/admin.py
> +    organization_name = fields.Field(attribute="converted_organization_name", column_name="organization_name")
@CocoByte have you tested the import/export fields? I would agree the Domain info Resource used for the import/export file doesn't need to be adjusted as that should just be purely what is in the database

2024-12-05 19:38 UTC, CocoByte commented on src/registrar/tests/test_reports.py
> +            "Portfolio 1 Federal Agency,,,, ,,(blank),"
Yes, I editted the data to make it clear when we are pulling from portfolio data or not.  adomain2 is affected across all these tests

2024-12-05 20:02 UTC, CocoByte commented on src/registrar/utility/csv_export.py
> -        }
Yes.  so_name was replaced by converted_so_name

2024-12-06 00:09 UTC, CocoByte commented on src/registrar/tests/test_reports.py
> +        self.maxDiff = None
We have these remnants in alot of places.  I'll clean them up

2024-12-06 00:23 UTC, merged