[DRAFT] #3129 - Tech Discovery On Renewal Form - [RH]
cisagov/manage.get.gov pull request #3273
Opened 2024-12-27 01:11 UTC by therealslimhsiehdy

## Ticket

Resolves #00

## Changes

- Change 1
- Change 2

** [Previous PR ](https://github.com/cisagov/manage.get.gov/pull/3248)

## Context for reviewers

## Setup

## Code Review Verification Steps

### As the original developer, I have

#### Satisfied acceptance criteria and met development standards

- [ ] Met the acceptance criteria, or will meet them in a subsequent PR
- [ ] Created/modified automated tests
- [ ] Update documentation in READMEs and/or onboarding guide

#### Ensured code standards are met (Original Developer)

- [ ] If any updated dependencies on Pipfile, also update dependencies in requirements.txt.
- [ ] Interactions with external systems are wrapped in try/except
- [ ] Error handling exists for unusual or missing values

#### Validated user-facing changes (if applicable)

- [ ] Tag @dotgov-designers in this PR's Reviewers for design review. If code is not user-facing, delete design reviewer checklist
- [ ] Verify new pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)

### As a code reviewer, I have

#### Reviewed, tested, and left feedback about the changes

- [ ] Pulled this branch locally and tested it
- [ ] Verified code meets all checks above. Address any checks that are not satisfied
- [ ] Reviewed this code and left comments. Indicate if comments must be addressed before code is merged
- [ ] Checked that all code is adequately covered by tests
- [ ] Verify migrations are valid and do not conflict with existing migrations

#### Validated user-facing changes as a developer
**Note:** Multiple code reviewers can share the checklists above, a second reviewer should not make a duplicate checklist. All checks should be checked before approving, even those labeled N/A. 

- [ ] New pages have been added to .pa11yci file so that they will be tested with our automated accessibility testing
- [ ] Checked keyboard navigability
- [ ] Meets all designs and user flows provided by design/product
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)
- [ ] (Rarely needed) Tested as both an analyst and applicant user

### As a designer reviewer, I have

#### Verified that the changes match the design intention

- [ ] Checked that the design translated visually
- [ ] Checked behavior. Comment any found issues or broken flows.
- [ ] Checked different states (empty, one, some, error)
- [ ] Checked for landmarks, page heading structure, and links

#### Validated user-facing changes as a designer

- [ ] Checked keyboard navigability
- [ ] Tested general usability, landmarks, page header structure, and links with a screen reader (such as Voiceover or ANDI)
- [ ] Tested with multiple browsers (check off which ones were used)
  - [ ] Chrome
  - [ ] Microsoft Edge
  - [ ] FireFox
  - [ ] Safari
- [ ] (Rarely needed) Tested as both an analyst and applicant user

### References
- [Code review best practices](../docs/dev-practices/code_review.md)

## Screenshots

2025-01-07 23:24 UTC, abroddrick commented on docs/developer/registry-access.md
> +
**nitpick** can we remove all the extra endlines?

2025-01-07 23:26 UTC, abroddrick commented on src/registrar/tests/test_views_domain.py
> +    def todays_expiration_date(self):
**suggestion** Maybe rename this function, it doesn't have return todays expiration date but an expiration date 1 year in the future

2025-01-07 23:26 UTC, therealslimhsiehdy commented on docs/developer/registry-access.md
> +
Omg not a nitpick at all, idk what happened here sorry -- great catch!

2025-01-07 23:30 UTC, abroddrick commented on src/registrar/models/domain.py
> -
**minor changes requested**: I see the renew code is logging errors below here but it is not printing the full traceback or the domain that threw the error. Please change both the RegistryError and normal exception to include traceback and domain name.

2025-01-07 23:32 UTC, abroddrick commented on src/registrar/views/domain.py
> +                messages.error(request, "This domain has not been renewed for one year, error was %s" % e)
You don't want to tell the user what the error was unless it helps them solve the problem on their own or will help them communicate the problem to us (such as an error code). I think here you would want to tell them to email help@get.gov if this problem persists. That way they have a clear action they can take.

2025-01-07 23:36 UTC, abroddrick commented on src/registrar/views/domain.py
> +        if is_policy_acknowledged != "on":
**question:** This is different than how we usually control validation, for every other page we use the form structure and have made sure to keep that pretty standard in the registrar. Why not change this to be a form with this as it's field so that it is checked on is_valid?

2025-01-08 00:00 UTC, therealslimhsiehdy commented on src/registrar/models/domain.py
> -
Would you mind elaborating or give an example of what you mean by traceback (I'm looking into our code for a pattern, but want to make sure I'm referencing the right area 😅)?

2025-01-08 00:59 UTC, kristinacyin commented
As discussed in #dotgov-design-reviews, I will do the first high-level pass review and another designer will take a look after. Deadline for PR review is Friday, 1/10.

2025-01-09 00:08 UTC, kristinacyin commented
Umm...tried to review but the domain is "Ready" even though the expiration date is today? 
![image](https://github.com/user-attachments/assets/8ef03865-9e46-41b4-82f1-53158c488cd9)

2025-01-09 07:19 UTC, kristinacyin requested changes
Amazing work! Noticed a few little discrepancies between the design and the implementation: 

- There should be 16px space below the H3 headers ("Your contact information", "Security email", and "Domain managers." 
- It also seems like the spacing between "None provided" text in the "Security email" section seems to be too big, compared to other sections? The spacing between the sections should be 32px. 
- The "Your contact information" section header should be in sentence case ("contact" and "information" should not be capitalized)

| Figma Design  | Implementation |
| ------------- | ------------- |
| ![tempsnip](https://github.com/user-attachments/assets/5173a336-518c-4655-ad26-f3afa5fc1960) | ![image](https://github.com/user-attachments/assets/2e42d943-b1ce-4f3c-a126-6187a521180a)  |

- It seems like the text for the "Expired" status alert hasn't been updated yet (has "Expiring soon" text)

| Figma Design  | Implementation |
| ------------- | ------------- |
| ![image](https://github.com/user-attachments/assets/05ac052b-948c-4edc-ba68-950a8e435625) | ![image](https://github.com/user-attachments/assets/62b2ec97-47d8-4889-9185-c760c31d73f4) |

**Potential bugs**
- With org model turned on, even though I didn't have any "Expiring soon" domains, I still saw the "Multiple domains are expiring" banner notification:
![image](https://github.com/user-attachments/assets/9a06297b-4663-4497-ae92-42c01f11a8d8)
- For some reason when I tried to update the security email, the Renewal Form will always show the Security email as "None provided"

2025-01-09 18:43 UTC, therealslimhsiehdy commented
@kristinacyin Thank you so much for the thorough review from the screenshots to the descriptions!

Below are responses to your comments:

> There should be 16px space below the H3 headers ("Your contact information", "Security email", and "Domain managers."

A small pushback - I matched the pattern to what we have on Domain Overview (so no spacing between the header and the text below) - although the design may look better with the spacing, code wise it would be a bit of a large override to match the Figma design so I did not make the spacing change.

> It also seems like the spacing between "None provided" text in the "Security email" section seems to be too big, compared to other sections? The spacing between the sections should be 32px.

Fixed! GREAT catch. Turns out it was a rogue p tag.

> The "Your contact information" section header should be in sentence case ("contact" and "information" should not be capitalized)

Fixed! 

> It seems like the text for the "Expired" status alert hasn't been updated yet (has "Expiring soon" text)

Fixed!

> The "Expiring soon" status is missing in the filter list options when the user doesn't have any "Expiring soon" domains. Given that the other status options are still shown even if the user doesn't have domains with all the different statuses, "Expiring soon" should still be shown regardless

Fixed!

> For some reason when I tried to update the security email, the Renewal Form will always show the Security email as "None provided"

Fixed -- huge thank you for catching this, was a backend code issue.

> There might also be a weird error where even though I checked the acknowledgement checkbox of the renewal form, it will still give me the error message as if I haven't. But it works when I check & submit the second time

Should be fixed - I think my sandbox is borked - please use Adit's `ad` sandbox for now. I will update the description and such to match that and add expiring and expired domains to her sandbox.

> With org model turned on, even though I didn't have any "Expiring soon" domains, I still saw the "Multiple domains are expiring" banner notification:

This is the only one I wasn't sure of -- could you happen to give me steps to replicate this? Not sure if this was an org model bug or my sandbox being a butthead bug.

2025-01-09 23:48 UTC, abroddrick commented on src/registrar/models/domain.py
> -
Oh no problem you just want to add exec_info=true on the logger line! [docs](https://docs.python.org/3/library/logging.html#logging.Logger.debug)
example from our code:
 `           logger.warning("Failed to send confirmation email", exc_info=True)`

2025-01-10 13:08 UTC, dave-kennedy-ecs commented on src/registrar/views/domain.py
> +        return False
If I read the code correctly, this method is inherited. Is that correct? Looks like an exact copy of the inherited method. If I am reading correctly, this method should not be redefined here.

2025-01-10 13:10 UTC, dave-kennedy-ecs commented on src/registrar/views/domain.py
> +        self.session = request.session
I am confused by the purpose of this override. Are you intending to reset the domain in cache each time the renewal form is requested?

2025-01-10 13:16 UTC, dave-kennedy-ecs commented on src/registrar/views/domain.py
> +class DomainRenewalView(DomainBaseView):
Curious why inherit DomainBaseView instead of DomainView? It looks like 4 of the 5 methods in DomainRenewalView are copied from DomainView. Couldn't you inherit DomainView, and then just define the template and post method?

2025-01-10 13:19 UTC, dave-kennedy-ecs submitted a review, later dismissed
I left some comments/questions on the view. Will re-evaluate once those are addressed.

2025-01-10 16:04 UTC, asaki222 commented on src/registrar/views/domain.py
> +class DomainRenewalView(DomainBaseView):
@dave-kennedy-ecs That is a good point! the `__get__domain` functionality that we used is also available in `DomainView`. I just pushed up the changes!

2025-01-10 16:23 UTC, kristinacyin commented
> @kristinacyin Thank you so much for the thorough review from the screenshots to the descriptions!
> 
> Below are responses to your comments:
> 
> > There should be 16px space below the H3 headers ("Your contact information", "Security email", and "Domain managers."
> 
> A small pushback - I matched the pattern to what we have on Domain Overview (so no spacing between the header and the text below) - although the design may look better with the spacing, code wise it would be a bit of a large override to match the Figma design so I did not make the spacing change.
> 
> > It also seems like the spacing between "None provided" text in the "Security email" section seems to be too big, compared to other sections? The spacing between the sections should be 32px.
> 
> Fixed! GREAT catch. Turns out it was a rogue p tag.
> 
> > The "Your contact information" section header should be in sentence case ("contact" and "information" should not be capitalized)
> 
> Fixed!
> 
> > It seems like the text for the "Expired" status alert hasn't been updated yet (has "Expiring soon" text)
> 
> Fixed!
> 
> > The "Expiring soon" status is missing in the filter list options when the user doesn't have any "Expiring soon" domains. Given that the other status options are still shown even if the user doesn't have domains with all the different statuses, "Expiring soon" should still be shown regardless
> 
> Fixed!
> 
> > For some reason when I tried to update the security email, the Renewal Form will always show the Security email as "None provided"
> 
> Fixed -- huge thank you for catching this, was a backend code issue.
> 
> > There might also be a weird error where even though I checked the acknowledgement checkbox of the renewal form, it will still give me the error message as if I haven't. But it works when I check & submit the second time
> 
> Should be fixed - I think my sandbox is borked - please use Adit's `ad` sandbox for now. I will update the description and such to match that and add expiring and expired domains to her sandbox.
> 
> > With org model turned on, even though I didn't have any "Expiring soon" domains, I still saw the "Multiple domains are expiring" banner notification:
> 
> This is the only one I wasn't sure of -- could you happen to give me steps to replicate this? Not sure if this was an org model bug or my sandbox being a butthead bug.

2025-01-10 21:05 UTC, asaki222 commented on src/registrar/models/domain.py
> -
Updated!

2025-01-10 21:54 UTC, kristinacyin approved these changes
There's a couple of things that need to be relegated to post-POD work, but great job! Can't believe we've accomplished so much in such a short amount of time.

2025-01-10 22:06 UTC, dave-kennedy-ecs commented on src/registrar/views/domain.py
> +        return False
One more. Looks like this one should also be deleted.

2025-01-10 22:50 UTC, dave-kennedy-ecs approved these changes
Approve, pending removal of the additional noted method in the view.

Thank you for all of the test cases in the PR notes. This was especially helpful for testing, and Rebecca was really helpful jumping on a call to walk through the PR

2025-01-13 19:09 UTC, merged